## Section I: Learn NumPy!
This [CS231n Numpy Tutorial](https://cs231n.github.io/python-numpy-tutorial/) tutorial might be useful for you. Please also check the official document at [NumPy: the absolute basics for beginners](https://numpy.org/devdocs/user/absolute_beginners.html).


In [ ]:
#Import numpy library as "np"
import numpy as np
#Now, if you want to use NumPy, just type `np` (instead of `numpy`)! 


### I.1. Warm-up:
- Using Numpy, let's initialize:
  $$
  \textbf{x} = (1.1, -5.2, 3) \\
  \textbf{A} = \begin{bmatrix} 4 & 3.2 &-2 \\ -1.2 & 2 & -1 \\ 4.3 & 2.1 & 1.4\end{bmatrix}
  $$
---
- What is the shape of $\textbf{A}$ and $\textbf{x}$?

In [ ]:
x=np.array([1.1, -5.2, 3])
A=np.array([[4,3.2,-2],
            [-1.2,2,-1],
            [4.3,2.1,1.4]])
print(np.shape(x))
print(np.shape(A))

(3,)
(3, 3)


### I.2. Array Initialization 
Create the following matrices:
*   $\textbf{B}$ is an identity matrix with shape $5 \times 5$
*   $\textbf{C}$ is an all-zeros matrix with shape $2 \times 3$
*   $\textbf{D}$ is an array with shape $5 \times 7 \times 3 $ filled with random values (Hint: using np.random)
*   $\textbf{E}$ is an all-ones matrix having the same shape as $\textbf{A}$ (don't type in the dimension of A manually!)
*   Suppose I have the following piece of code:
```
a = x      # initialize array a equal to x 
a[0] = 0.5 # change the first element of a into 0.5
print(a)   # the output is [ 0.5 -5.2  3. ]. Happy!
```
Now, let's print the value of `x`, what happened with `x`? How to fix this issue?

In [ ]:
B=np.identity(5)
C=np.zeros([2,3])
D=np.random.random([5,7,3])
E=np.ones(np.shape(A))
print(E)
#when assign a = x, change to a will also change to x, so we need to use np.copy() method
a=np.copy(x)     # initialize array a equal to x 
a[0] = 0.5 # change the first element of a into 0.5
print(a)   # the output is [ 0.5 -5.2  3. ]. Happy!
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0.5 -5.2  3. ]
[ 1.1 -5.2  3. ]


### I.3. Array Indexing
Using NumPy, let's create a random matrix $\textbf{F}$ with shape $5\times 7$. 

---

Answer the following questions:
*   What is the value of the second element of the first row?
*   What is the third column of matrix $\textbf{A}$?
*   What is the last row of matrix $\textbf{B}$?
*   Let's decompose $\textbf{F}$ into the following sub-matricies. Find all $\textbf{F}_{1 \rightarrow 5}$.
$$
\begin{bmatrix}
    F_1^{(3 \times 3)}  & \begin{matrix} F_2^{(1 \times 4)} \\ F_3^{(2 \times 4)} \end{matrix} \\
     F_4^{(2 \times 4)} & F_5^{(2 \times 3)}
\end{bmatrix}
$$
*  Calculate the sum of the last two elements in the second column of $\textbf{F}$ 


In [ ]:
F=np.random.random([5,7])
print(A[2])
print(B[:,-1])
print(F)
F1=F[0:3,0:3]
F4=F[3:,:4]
F2=F[:1,3:]
F3=F[1:3,3:]
F5=F[3:,4:]
print(f"Matrix F1: {F1}")
print(f"Matrix F2: {F2}")
print(f"Matrix F3: {F3}")
print(f"Matrix F4: {F4}")
print(f"Matrix F5: {F5}")
print(f"The sum of the last two elements in the second column of F: {np.sum(F[-2:,1])}")

[4.3 2.1 1.4]
[0. 0. 0. 0. 1.]
[[0.83643397 0.11206477 0.19794877 0.2778309  0.87008822 0.19994032
  0.4025266 ]
 [0.18875047 0.17920618 0.85628232 0.40869511 0.22649216 0.40430152
  0.3653373 ]
 [0.43731094 0.88668263 0.40062088 0.9118384  0.31674321 0.23069114
  0.94902634]
 [0.67554685 0.59226885 0.27568947 0.27771854 0.9804286  0.90816663
  0.87906464]
 [0.97573106 0.50588187 0.72261753 0.3858016  0.91303478 0.25560634
  0.92650013]]
Matrix F1: [[0.83643397 0.11206477 0.19794877]
 [0.18875047 0.17920618 0.85628232]
 [0.43731094 0.88668263 0.40062088]]
Matrix F2: [[0.2778309  0.87008822 0.19994032 0.4025266 ]]
Matrix F3: [[0.40869511 0.22649216 0.40430152 0.3653373 ]
 [0.9118384  0.31674321 0.23069114 0.94902634]]
Matrix F4: [[0.67554685 0.59226885 0.27568947 0.27771854]
 [0.97573106 0.50588187 0.72261753 0.3858016 ]]
Matrix F5: [[0.9804286  0.90816663 0.87906464]
 [0.91303478 0.25560634 0.92650013]]
The sum of the last two elements in the second column of F: 1.0981507270417876


### I.4 Array Operators
Using NumPy, let's create a random matrix $\textbf{G}$ with shape $5\times 5$. 

---
* Calculate $\textbf{G+B}, \frac{1}{2}\textbf{A}$
* How to add $0.5$ to every elements on the main diagonal of matrix $\textbf{A}$?
* Calculate $\textbf{G} \odot B$ (element-wise product), $\textbf{GB}$ and $\textbf{CA}$ (matrix multiplication)
* Calculate $A^{-1}$ (matrix inversion)
* Suppose $\textbf{x}$ from the warm-up question is now a column vector, calculate the following values: $\textbf{A}\textbf{x}, \textbf{x}\textbf{x}^\top$


In [ ]:
G=np.random.random([5,5])
A1=np.identity(3)
print(f"Product of G+B:\n{np.add(G,B)}")
print(f"1/2 A:\n{0.5*A}")
print(f"Add 0.5 to every elements of A\n{A+0.5*A1}")
print(f"Element-wise product of G and B:\n{np.multiply(G,B)}")
print(f"GB:\n{G.dot(B)}")
print(f"CA:\n{C.dot(A)}")
print(np.linalg.inv(A))
print(A.dot(x))
print(x.transpose().dot(x))


Product of G+B:
[[1.01273329 0.73977369 0.03344771 0.70921747 0.71036069]
 [0.83163337 1.64892802 0.79481918 0.66011327 0.93593288]
 [0.92137878 0.4786418  1.49570325 0.29893299 0.40593864]
 [0.89719058 0.66773621 0.95216009 1.94414996 0.72454546]
 [0.40150497 0.21629391 0.22932396 0.59601643 1.66808893]]
1/2 A:
[[ 2.    1.6  -1.  ]
 [-0.6   1.   -0.5 ]
 [ 2.15  1.05  0.7 ]]
Add 0.5 to every elements of A
[[ 4.5  3.2 -2. ]
 [-1.2  2.5 -1. ]
 [ 4.3  2.1  1.9]]
Element-wise product of G and B:
[[0.01273329 0.         0.         0.         0.        ]
 [0.         0.64892802 0.         0.         0.        ]
 [0.         0.         0.49570325 0.         0.        ]
 [0.         0.         0.         0.94414996 0.        ]
 [0.         0.         0.         0.         0.66808893]]
GB:
[[0.01273329 0.73977369 0.03344771 0.70921747 0.71036069]
 [0.83163337 0.64892802 0.79481918 0.66011327 0.93593288]
 [0.92137878 0.4786418  0.49570325 0.29893299 0.40593864]
 [0.89719058 0.66773621 0.95216009

### I.5. Array Axis
Firstly, please visit this [link](https://www.sharpsightlabs.com/blog/numpy-axes-explained/#:~:text=NumPy%20axes%20are%20the%20directions,along%20the%20rows%20and%20columns.) or every online resource that you prefer to understand about the *axis* in NumPy array.

---

* What does `F.sum(axis=1)`do to $\textbf{F}$? What is the shape of the result array?
* Calculate the average of every element in $\textbf{F}$
* Calculate the average of every row in $\textbf{F}$
* Find the largest element of each column in $\textbf{F}$
* Find the position of the smallest element in each row of $\textbf{F}$


In [ ]:
print(F.sum(axis=1))
print(np.shape(F.sum(axis=1)))

print(np.shape(F.sum(axis=1)))

print(F.sum(axis=1).sum()/np.prod(np.shape(F)))

print(F.max(axis=0))

min_pos = np.argmin(F, axis=1)

[2.89683355 2.62906507 4.13291353 4.58888357 4.68517331]
(5,)
(5,)
0.5409391152258864
[0.97573106 0.88668263 0.85628232 0.9118384  0.9804286  0.90816663
 0.94902634]


### I.6. Array Manipulation
* Flatten the array $\textbf{C}$
* Create matrix $\textbf{H} = \left[\textbf{F}|\textbf{B}\right]$ (stacking matrix $\textbf{B}$ on the right side of matrix $\textbf{F}$). Hint: using `np.hstack`
* Create matrix $\textbf{J} (3\times6)$ by stacking column vector $\textbf{x}$ 6 times. Hint: using `np.repeat`, and you also need to add an "extra" dimension into `x`, so `x.shape = (3,1)` not `(3,)`!
* Reshape matrix $\textbf{J}$ into a $2 \times 9$ matrix. Hint: using `np.reshape`

In [ ]:
C.flatten()
print(C)

H=np.concatenate((F,B),axis=1)
print(H)

xn=np.expand_dims(x,axis=0)
xn=xn.transpose()
J=np.repeat(xn,6,axis=1)
print(J)

J=J.reshape(2,9)
print(J)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0.83643397 0.11206477 0.19794877 0.2778309  0.87008822 0.19994032
  0.4025266  1.         0.         0.         0.         0.        ]
 [0.18875047 0.17920618 0.85628232 0.40869511 0.22649216 0.40430152
  0.3653373  0.         1.         0.         0.         0.        ]
 [0.43731094 0.88668263 0.40062088 0.9118384  0.31674321 0.23069114
  0.94902634 0.         0.         1.         0.         0.        ]
 [0.67554685 0.59226885 0.27568947 0.27771854 0.9804286  0.90816663
  0.87906464 0.         0.         0.         1.         0.        ]
 [0.97573106 0.50588187 0.72261753 0.3858016  0.91303478 0.25560634
  0.92650013 0.         0.         0.         0.         1.        ]]
[[ 1.1  1.1  1.1  1.1  1.1  1.1]
 [-5.2 -5.2 -5.2 -5.2 -5.2 -5.2]
 [ 3.   3.   3.   3.   3.   3. ]]
[[ 1.1  1.1  1.1  1.1  1.1  1.1 -5.2 -5.2 -5.2]
 [-5.2 -5.2 -5.2  3.   3.   3.   3.   3.   3. ]]


### I.7. Array Masking & Broadcasting
We have provided matrix $\textbf{K}$ and vector $\textbf{y}$ for you as below

---

*   Construct matrix $\textbf{L}$, where $\textbf{L}_{ij} = True$ if $\textbf{K}_{ij}\mod 2=0$ and $\textbf{L}_{ij} = False$ otherwise
*   Matrix $\textbf{M}$ is constructed by flipping the sign of every odd element in $\textbf{K}$ to the negative one. Find $\textbf{M}$. Hint: using $\textbf{L}$ and [this link](https://numpy.org/devdocs/reference/arrays.indexing.html)
* Subtract every element of the first row in $\textbf{K}$ by $\textbf{x}_1$, the second one by $\textbf{x}_2$ and the last one by $\textbf{x}_3$ (elements of column vector $\textbf{x}$ in the first question). Hint: check "NumPy broadcasting", you should create an "extra" dimension as in the previous question
* Construct matrix $\textbf{N}$, where $\textbf{N}_{ij} = \textbf{x}_i + \textbf{y}_j$ (row $i$, column $j$). Hint: check "NumPy broadcasting", $\textbf{N}$ is $3\times 4$ matrix






In [ ]:
K = np.random.randint(1,10, size=(3,5))
L=np.zeros((3,5),dtype=bool)
for i in range(3):
  for j in range(5):
    if K[i,j]%2==0:
      L[i,j]=True
    else:
      L[i,j]=False
      
print(K)
print(L)
M=K*-1
M[L]*=-1
print(M)

x.shape=(3,1)
print(K-x)

y = np.array([1,-2.3,-5,4.5])
x.shape=(3,1)
N = x + y
print(N)
#TYPE YOUR ANSWER HERE

[[3 7 3 4 3]
 [4 4 7 5 6]
 [2 4 1 9 6]]
[[False False False  True False]
 [ True  True False False  True]
 [ True  True False False  True]]
[[-3 -7 -3  4 -3]
 [ 4  4 -7 -5  6]
 [ 2  4 -1 -9  6]]
[[ 1.9  5.9  1.9  2.9  1.9]
 [ 9.2  9.2 12.2 10.2 11.2]
 [-1.   1.  -2.   6.   3. ]]
[[  2.1  -1.2  -3.9   5.6]
 [ -4.2  -7.5 -10.2  -0.7]
 [  4.    0.7  -2.    7.5]]


# Section II: Python Review

## II.1 Matrix Multiplication Without NumPy
In the previous section, you can do matrix multiplication in just 1 line of code. Now, just using nested `list` in Python to create a matrix, let's implement the matrix multiplication again with the `for` loop. Your implementation should work for every size, but now just calculate the matrix multiplication between a $3\times4$ and $4\times 5$ matrix and print out the result.

In [ ]:
def matrix_multiplication_for_loop(matA, matB):
  matC=[]
  for i in range(len(matA[0])):
    lstc = []
    for j in range(len(matB[0])):
      temp = 0
      for k in range(len(matB)):
        temp += matA[i][k] * matB[k][j]
      lstc.append(temp)
    matC.append(lstc)
  return matC


Now, let's test your implement with two $300\times300$ matrix and compare the execution time with NumPy. We have prepared the code for you, implement `matrix_multiplication_numpy` and execute the cell. What is your expectation of the result?

In [ ]:
import time
def matrix_multiplication_numpy(matA, matB):
  return matA.dot(matB)
  pass

def measure_execution_time(func, matA, matB):
  t0= time.time()
  func(matA, matB)
  t1 = time.time() - t0
  print("Time elapsed: {} sec.".format(t1))

X = np.random.rand(300,300)
Y = np.random.rand(300,300)
print("Using NumPy: ")
measure_execution_time(matrix_multiplication_numpy,X, Y)

print("Using For-loop: ")
measure_execution_time(matrix_multiplication_for_loop,X.tolist(), Y.tolist())

Using NumPy: 
Time elapsed: 0.012448787689208984 sec.
Using For-loop: 
Time elapsed: 7.3422205448150635 sec.


That's it! Imagine what will happen if you need to work on an RGB HD image (which is $1080\times 1920 \times 3$)!. 

This is just an example, you can look up the term *verctorization*, which is a technique used to speed up the code by avoid using for-loop. **From now, try to use NumPy as much as possible!!!**

## II.2. Basic OOP
Let define a `Rectangle` class. A rectangle in a 2D coordinate system is defined by the top-left and bottom-right corner. Class `Point` has already been defined for you.

---

Implement the following methods:

* `get_area()`: return the area of the rectangle 
* `is_larger(rect)`: return `True` if the area is larger than the input rectangle `rect`
*  Implement the `iou(rect)` to calcuate the intersection over union between two rectangles

Then:
* Initialize a list of 5 rectangles, with the positions of your choice
* Sort the list by the area of each rectangle, in ascending order

In [ ]:
class Point:
  def __init__(self, x, y):
    self.x = x
    self.y = y

class Rectangle():
  def __init__(self,P1,P2):
    self.x = P1.x
    self.y = P1.y
    self.z = P2.x
    self.t = P2.y

  def get_area(self):
    a=abs(self.x-self.z)
    b=abs(self.y-self.t)
    return a*b 

  def is_larger(self, rect):
    if self.get_area()>rect.get_area():
      return True
    else: 
      return False 

P1 = Point(1,2)
P2 = Point(4,8)
P3 = Point(5,3)
P4 = Point(42,342)
P5 = Point(564,2233)
P6 = Point(56,5234)
P7 = Point(441,53)
P8 = Point(246,6334)
P9 = Point(134,6345)
P10 = Point(345,787)

rec1 = Rectangle(P1,P2)
rec2 = Rectangle(P3,P4)
rec3 = Rectangle(P5,P6)
rec4 = Rectangle(P7,P8)
rec5 = Rectangle(P9,P10)
lst=[rec1.get_area(),rec2.get_area(),rec3.get_area(),rec4.get_area(),rec5.get_area()]
lst=sorted(lst)
print(lst)





[18, 12543, 1172738, 1224795, 1524508]
